[package]
name = "east-guard"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.97"
tokio = { version = "1.44.2", features = ["full"] }
clap = { version = "4.5", features = ["derive", "env"] }
bytes = "1.10.1"
bincode = { version = "2.0.1" }
rand = "0.8"
murmur3 = { version = "0.5" }
